name: Flask CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
            
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pipenv'

      - name: Install Pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --deploy --dev

      - name: Run tests
        run: pipenv run pytest